name: Test Email Step

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 24f1002326@ds.study.iitm.ac.in
        run: echo "Hello, this is a test step!"
