name: Test Action

on:
  push:
    branches:
      - main  # or the branch you are working on
  workflow_dispatch:  # allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 24f1002326@ds.study.iitm.ac.in
        run: echo "Hello, world!"
